#if defined _WCORE_INCLUDED
    #endinput
#endif
#define _WCORE_INCLUDED

// ============================================================================
// Wasteland SA
// Core Engine
// ============================================================================

stock WCore_Init()
{
    print(" ");
    print("==============================================");
    print("        Wasteland SA - WEngine");
    print("==============================================");
    print(" Core.................OK");
    print(" Version..............0.0.1 Alpha");
    print("==============================================");
    print(" ");

    return 1;
}